data_dir = 'data/datasets/catez/catez_masters'
first_channel = 0
last_channel = 7
load_events = false
test = 0.2
epoch = [200]
batch = [16]
lr = [0.0002]
seeds = [1, 2, 3, 4, 5, 6, 7, 8, 9, 42]
#model = "0.2.0.dev14+2a4fbf3.master-classifier-0.0002-200-16" # Best model1
#model = "0.2.0.dev10+c55f52e.master-classifier-aug-0.0001-200-32" # Best model1-aug
#model = "0.4.0.dev4+58483c9.master-classifier-aug-0.0002-200-16-5" # Best model1-aug if ignoring hyperparameter optimisation (consistency)
#model = "0.2.0.dev12+a904b8e.master-classifier3-0.0005-200-16" # Best model2
#model = "0.4.0.dev2+130d145.master-classifier2-aug-5e-05-200-16-4" # Best model2-aug
#model = "0.2.0.dev11+8ca4177.master-classifier2-5e-05-200-32" # Best model3
#model = "0.3.0.dev9+a6efef5.master-classifier3-aug-0.0005-200-32-3"  # Best model3-aug