data_dir = 'data/datasets/catez/catez_masters'
first_channel = 0
last_channel = 7
load_events = false
test = 0.2
epoch = [100, 200]
batch = [16, 32]
lr = [0.00005, 0.0001, 0.0002, 0.0003, 0.0005, 0.001]
seeds = [1, 2, 3, 4, 42]
#model = "0.2.0.dev14+2a4fbf3.master-classifier-0.0002-200-16" # Best model1
#model = "0.2.0.dev10+c55f52e.master-classifier-aug-0.0001-200-32" # Best model1-aug
#model = "0.2.0.dev12+a904b8e.master-classifier3-0.0005-200-16" # Best model2
#model = "0.2.0.dev11+8ca4177.master-classifier2-5e-05-200-32" # Best model3